#!/bin/bash
#
# Bluespec Simulation Driver
#
set -e

function usage 
{
    echo "Usage: $1 [-m <maxcycles>] [--model <pg101|pg103>] <elf_binaryfile>"
}

MAX_CYCLES=""
MODEL="<not specified>"
INPUT=""
CHECK=""

while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        --max-cycles)
            MAX_CYCLES="-m $2"
            shift # past argument
            shift # past value
            ;;
        --model)
            MODEL="$2"
            shift # past argument
            shift # past value
            ;;
        --log)
            export INSTRUCTION_LOG_FILENAME="$2"
            shift
            shift
            ;;
        --check)
            CHECK="True"
            shift
            ;;
        *)
            # If it's a directory, assume it's an input file
            POSITIONAL+=("$1")
            shift # past argument
            ;;
  esac
done

if [ ${#POSITIONAL[@]} -eq 0 ]; then
    usage
    exit 1;
fi

export INPUT_FILE="${POSITIONAL[0]}"
export PROGRAM_MEMORY_FILE="$INPUT_FILE" 

if [ "$CHECK" == "" ]; then
    ./build/$MODEL/src/PG10x/Simulator/Simulator $MAX_CYCLES
else
    if ./build/$MODEL/src/PG10x/Simulator/Simulator $MAX_CYCLES | grep '    PASS'; then
        exit 0
    else
        exit 1
    fi
fi
